### ISSUE TITLE
Incorrect Parentheses

### ISSUE THREAD

**Issue by rinz13r** [JdeRobot/PyOnArduino#17]
The following snippet
```
def f():
    if (true):
        return 1
```

produces

```
void f( ) {
    if (true return ;
}
}
```

Also the following snippet
```
def f():
    if (1+1 == 2):
        a = 1
        return 1
```
produces
```
void f() {
if (((1 + 1) == 2)DynType a;a.tvar = INT;String har0 = "1";har0.toCharArray(a.data, MinTypeSz);
  return ;
}
}
```

Looks like string ") {" (after the condition in the if statement) is not appended.

**Comment by rinz13r** [comment]
My understanding is that after an _if statement_ is encountered, the job of balancing the parentheses is up to other visitors.
`vars.is_if` is set to true, once an _if statement_ is encountered and other visitors append the string ") {" if `(vars.is_if == True)`. Now, if I'm not wrong, that condition is not being checked at many places (such as visit_Expr, visit_Compare, etc.) leading to such an error.
One solution is to update the implementation to make specifics such as ") {" localized in the appropriate visitors. In this case, we append _"("_ before and _") {"_ after parsing the predicate. Then we make a call to generic_visit for visiting the condition. However, this would break the existing code at multiple places. But this approach would allow for future constructs to be added without much hassle.

The other solution is to add ") {" at appropriate places by checking if `(vars.is_if == True)`. However, this approach is error-prone and would lead to multiple code redundancies.

I would like to know what you think.

**Comment by sergiopaniego** [comment]
I see your point and I think your solution could be interesting to be implemented in order to get rid of this error now and future ones. You can code the approach if you want to and we can discuss it having the code 😄

**Comment by sergiopaniego** [comment]
Merged pull request and problem solved 😄
