### ISSUE TITLE
Extension of HALduino to support communication device

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/PyOnArduino#6]

**Comment by GrayR00t** [comment]
I would like to work on this feature please let know me necessary information

**Comment by aker99** [comment]
Sir, I wanna work on  this project as my GSoC'19 project, please guide me with further details

**Comment by jmplaza** [comment]
@aker99 this is NOT the way to ask for information about [GSoC'19 projects](https://jderobot.org/GSoC-2019), just follow the [application instructions](https://jderobot.org/GSoC-2019#Application_instructions_for_GSoC-2019) and contact the corresponding mentors after doing the programming tests and submitting the Google Form.
